# Generated by Django 5.0.14 on 2026-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="yahoo", max_length=50)),
                ("source", models.CharField(max_length=100)),
                ("article_url", models.URLField(unique=True)),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("published", models.DateTimeField(db_index=True)),
                ("title", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ["-published"],
                "indexes": [
                    models.Index(
                        fields=["provider", "published"],
                        name="news_article_provider_published_idx",
                    ),
                    models.Index(
                        fields=["provider", "source"],
                        name="news_article_provider_source_idx",
                    ),
                ],
            },
        ),
    ]
