# Generated by Django 6.0.1 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="language",
            field=models.CharField(db_index=True, default="en", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="fetched_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
