# Generated by Django 6.0.1 on 2026-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsarticle_language_newsarticle_fetched_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="newsarticle",
            new_name="news_newsar_provide_fdeeba_idx",
            old_name="news_article_provider_published_idx",
        ),
        migrations.RenameIndex(
            model_name="newsarticle",
            new_name="news_newsar_provide_fcd357_idx",
            old_name="news_article_provider_source_idx",
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="fetched_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
