# Generated by Django 6.0.1 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_rename_news_article_provider_published_idx_news_newsar_provide_fdeeba_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="content_hash",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
