# Generated by Django 6.0.1 on 2026-04-01

import pgvector.django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newsarticle_content_hash"),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name="NewsArticleEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("chunk_text", models.TextField()),
                ("chunk_hash", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=500)),
                ("source", models.CharField(max_length=100)),
                ("published", models.DateTimeField(db_index=True)),
                ("embedding_model", models.CharField(max_length=100)),
                ("embedding", pgvector.django.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="news.txt.newsarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["article_id", "chunk_index", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "chunk_index"),
                        name="uniq_news_article_chunk",
                    )
                ],
            },
        ),
    ]
