# Generated by Django 5.0.14 on 2026-03-03 18:05

import inspect
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.db.models import Q


def _check_kwargs(expr: Q) -> dict:
    params = inspect.signature(models.CheckConstraint.__init__).parameters
    if "condition" in params:
        return {"condition": expr}
    return {"check": expr}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("investment", "0003_remove_investmentaccountsnapshot_inv_acc_snap_acc_lvl_time_idx_and_more"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="InvestmentAccountSnapshot",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("snapshot_time", models.DateTimeField(db_index=True)),
                        (
                            "snapshot_level",
                            models.CharField(
                                choices=[
                                    ("M15", "15分钟"),
                                    ("H4", "4小时"),
                                    ("D1", "1天"),
                                    ("MON1", "1月"),
                                ],
                                default="M15",
                                max_length=8,
                            ),
                        ),
                        (
                            "currency",
                            models.CharField(
                                choices=[
                                    ("CNY", "人民币"),
                                    ("USD", "美元"),
                                    ("JPY", "日元"),
                                    ("EUR", "欧元"),
                                    ("HKD", "港币"),
                                ],
                                default="USD",
                                max_length=3,
                            ),
                        ),
                        ("total_asset", models.DecimalField(decimal_places=6, max_digits=20)),
                        (
                            "data_status",
                            models.CharField(
                                choices=[("ok", "正常"), ("quote_missing", "缺少行情")],
                                default="ok",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "account",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="investment_account_snapshots",
                                to="accounts.accounts",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "investment_account_snapshot",
                        "indexes": [
                            models.Index(
                                fields=["snapshot_level", "snapshot_time"],
                                name="inv_acc_snap_lvl_time_idx",
                            )
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("account", "snapshot_level", "snapshot_time"),
                                name="uniq_inv_acc_snapshot_lvl",
                            ),
                            models.CheckConstraint(
                                **_check_kwargs(Q(("total_asset__gte", 0))),
                                name="inv_acc_snapshot_total_asset_gte_0",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="InvestmentPositionSnapshot",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("snapshot_time", models.DateTimeField(db_index=True)),
                        (
                            "snapshot_level",
                            models.CharField(
                                choices=[
                                    ("M15", "15分钟"),
                                    ("H4", "4小时"),
                                    ("D1", "1天"),
                                    ("MON1", "1月"),
                                ],
                                default="M15",
                                max_length=8,
                            ),
                        ),
                        (
                            "quantity",
                            models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=20),
                        ),
                        (
                            "avg_cost",
                            models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=20),
                        ),
                        (
                            "market_price",
                            models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                        ),
                        (
                            "market_value",
                            models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                        ),
                        (
                            "realized_pnl",
                            models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=20),
                        ),
                        ("price_time", models.DateTimeField(blank=True, null=True)),
                        (
                            "currency",
                            models.CharField(
                                choices=[
                                    ("CNY", "人民币"),
                                    ("USD", "美元"),
                                    ("JPY", "日元"),
                                    ("EUR", "欧元"),
                                    ("HKD", "港币"),
                                ],
                                default="USD",
                                max_length=3,
                            ),
                        ),
                        (
                            "data_status",
                            models.CharField(
                                choices=[("ok", "正常"), ("quote_missing", "缺少行情")],
                                default="ok",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "account",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="investment_position_snapshots",
                                to="accounts.accounts",
                            ),
                        ),
                        (
                            "instrument",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="investment_position_snapshots",
                                to="market.instrument",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "investment_position_snapshot",
                        "indexes": [
                            models.Index(
                                fields=["account", "snapshot_level", "snapshot_time"],
                                name="inv_pos_acc_lvl_time_idx",
                            ),
                            models.Index(
                                fields=["snapshot_level", "snapshot_time"],
                                name="inv_pos_snap_lvl_time_idx",
                            ),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("account", "instrument", "snapshot_level", "snapshot_time"),
                                name="uniq_inv_pos_snapshot_lvl",
                            ),
                            models.CheckConstraint(
                                **_check_kwargs(Q(("quantity__gte", 0))),
                                name="inv_pos_snapshot_quantity_gte_0",
                            ),
                            models.CheckConstraint(
                                **_check_kwargs(Q(("avg_cost__gte", 0))),
                                name="inv_pos_snapshot_avg_cost_gte_0",
                            ),
                            models.CheckConstraint(
                                **_check_kwargs(
                                    Q(("market_price__isnull", True))
                                    | Q(("market_price__gt", 0))
                                ),
                                name="inv_pos_snapshot_market_price_null_or_gt_0",
                            ),
                            models.CheckConstraint(
                                **_check_kwargs(
                                    Q(("market_value__isnull", True))
                                    | Q(("market_value__gte", 0))
                                ),
                                name="inv_pos_snapshot_market_value_null_or_gte_0",
                            ),
                            models.CheckConstraint(
                                **_check_kwargs(
                                    Q(
                                        ("data_status", "ok"),
                                        ("market_price__isnull", False),
                                        ("market_value__isnull", False),
                                    )
                                    | Q(("data_status", "quote_missing"))
                                ),
                                name="inv_pos_snapshot_status_price_consistent",
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]
