# Generated by Django 5.0.14 on 2026-03-03 18:04

import inspect
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.db.models import Q


def _check_kwargs(expr: Q) -> dict:
    params = inspect.signature(models.CheckConstraint.__init__).parameters
    if "condition" in params:
        return {"condition": expr}
    return {"check": expr}


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("market", "0001_initial"),
        ("snapshot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentpositionsnapshot",
            name="account",
        ),
        migrations.RemoveField(
            model_name="investmentpositionsnapshot",
            name="instrument",
        ),
        migrations.CreateModel(
            name="AccountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_time", models.DateTimeField(db_index=True)),
                (
                    "snapshot_level",
                    models.CharField(
                        choices=[
                            ("M15", "15分钟"),
                            ("H4", "4小时"),
                            ("D1", "1天"),
                            ("MON1", "1月"),
                        ],
                        default="M15",
                        max_length=8,
                    ),
                ),
                (
                    "account_currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "balance_native",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("balance_usd", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "fx_rate_to_usd",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("ok", "正常"),
                            ("quote_missing", "缺少行情"),
                            ("fx_missing", "缺少汇率"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_snapshots",
                        to="accounts.accounts",
                    ),
                ),
            ],
            options={
                "db_table": "snapshot_account_snapshot",
            },
        ),
        migrations.CreateModel(
            name="PositionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_time", models.DateTimeField(db_index=True)),
                (
                    "snapshot_level",
                    models.CharField(
                        choices=[
                            ("M15", "15分钟"),
                            ("H4", "4小时"),
                            ("D1", "1天"),
                            ("MON1", "1月"),
                        ],
                        default="M15",
                        max_length=8,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "market_value_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "fx_rate_to_usd",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("price_time", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("ok", "正常"),
                            ("quote_missing", "缺少行情"),
                            ("fx_missing", "缺少汇率"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_snapshots",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_snapshots",
                        to="market.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "snapshot_position_snapshot",
            },
        ),
        migrations.DeleteModel(
            name="InvestmentAccountSnapshot",
        ),
        migrations.DeleteModel(
            name="InvestmentPositionSnapshot",
        ),
        migrations.AddIndex(
            model_name="accountsnapshot",
            index=models.Index(
                fields=["snapshot_level", "snapshot_time"], name="snap_acc_lvl_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "snapshot_level", "snapshot_time"),
                name="uniq_snap_acc_lvl_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("fx_rate_to_usd__isnull", True),
                    ("fx_rate_to_usd__gt", 0),
                    _connector="OR",
                )),
                name="snap_acc_fx_rate_null_or_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="positionsnapshot",
            index=models.Index(
                fields=["account", "snapshot_level", "snapshot_time"],
                name="snap_pos_acc_lvl_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="positionsnapshot",
            index=models.Index(
                fields=["snapshot_level", "snapshot_time"], name="snap_pos_lvl_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "instrument", "snapshot_level", "snapshot_time"),
                name="uniq_snap_pos_inst_lvl_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("quantity__gte", 0))), name="snap_pos_quantity_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("avg_cost__gte", 0))), name="snap_pos_avg_cost_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("market_price__isnull", True),
                    ("market_price__gt", 0),
                    _connector="OR",
                )),
                name="snap_pos_market_price_null_or_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("market_value__isnull", True),
                    ("market_value__gte", 0),
                    _connector="OR",
                )),
                name="snap_pos_market_value_null_or_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("market_value_usd__isnull", True),
                    ("market_value_usd__gte", 0),
                    _connector="OR",
                )),
                name="snap_pos_market_usd_null_or_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("fx_rate_to_usd__isnull", True),
                    ("fx_rate_to_usd__gt", 0),
                    _connector="OR",
                )),
                name="snap_pos_fx_rate_null_or_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    models.Q(
                        ("data_status", "ok"),
                        ("market_price__isnull", False),
                        ("market_value__isnull", False),
                    ),
                    ("data_status", "quote_missing"),
                    ("data_status", "fx_missing"),
                    _connector="OR",
                )),
                name="snap_pos_status_price_consistent",
            ),
        ),
    ]
