# Generated by Django 6.0.1 on 2026-03-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snapshot", "0002_remove_investmentpositionsnapshot_account_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountsnapshot",
            options={"verbose_name": "账户快照", "verbose_name_plural": "账户快照"},
        ),
        migrations.AlterModelOptions(
            name="positionsnapshot",
            options={"verbose_name": "持仓快照", "verbose_name_plural": "持仓快照"},
        ),
    ]
