# Generated by Django 5.0.14 on 2026-03-03 17:11

import inspect
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def _check_kwargs(expr: Q) -> dict:
    params = inspect.signature(models.CheckConstraint.__init__).parameters
    if "condition" in params:
        return {"condition": expr}
    return {"check": expr}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="标准代码",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="原始代码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="品种名称"
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("STOCK", "股票 (Stock)"),
                            ("CRYPTO", "加密货币 (Crypto)"),
                            ("FOREX", "外汇 (Forex)"),
                        ],
                        default="STOCK",
                        max_length=20,
                        verbose_name="资产大类",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("US", "美股 (United States)"),
                            ("CN", "A股 (China)"),
                            ("HK", "港股 (Hong Kong)"),
                            ("CRYPTO", "加密货币市场 (Crypto)"),
                            ("FX", "外汇市场 (Forex)"),
                        ],
                        default="US",
                        max_length=20,
                        verbose_name="所属市场",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="交易所"
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="计价货币"
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Logo URL"
                    ),
                ),
                (
                    "logo_color",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Logo 主题色"
                    ),
                ),
                (
                    "logo_source",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Logo 来源"
                    ),
                ),
                (
                    "logo_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Logo 更新时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="用于标记退市股票或下架品种",
                        verbose_name="是否可交易",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "交易品种",
                "verbose_name_plural": "交易品种列表",
                "db_table": "market_instrument",
                "ordering": ["asset_class", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["short_code", "name"],
                        name="market_inst_short_c_cb36ea_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInstrumentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_position", models.BooleanField(default=False)),
                ("from_watchlist", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriptions",
                        to="market.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "market_user_instrument_subscription",
                "indexes": [
                    models.Index(fields=["instrument"], name="mkt_sub_instrument_idx"),
                    models.Index(
                        fields=["user", "updated_at"], name="mkt_sub_user_updated_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userinstrumentsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "instrument"), name="uniq_user_instrument_subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinstrumentsubscription",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("from_position", True), ("from_watchlist", True), _connector="OR"
                )),
                name="sub_at_least_one_source_true",
            ),
        ),
    ]
