# Generated by Django 6.0.1 on 2026-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("STOCK", "股票 (Stock)"),
                    ("INDEX", "指数 (Index)"),
                    ("CRYPTO", "加密货币 (Crypto)"),
                    ("FOREX", "外汇 (Forex)"),
                ],
                default="STOCK",
                max_length=20,
                verbose_name="资产大类",
            ),
        ),
    ]
