# Generated by Django 5.0.14 on 2026-03-01 12:00

import inspect
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from django.db.utils import ProgrammingError


def _check_kwargs(expr: Q) -> dict:
    params = inspect.signature(models.CheckConstraint.__init__).parameters
    if "condition" in params:
        return {"condition": expr}
    return {"check": expr}


def _backfill_subscriptions(apps, schema_editor):
    subscription_model = apps.get_model("market", "UserInstrumentSubscription")
    watchlist_model = apps.get_model("accounts", "WatchlistItem")
    position_model = apps.get_model("investment", "Position")
    db_alias = schema_editor.connection.alias

    states: dict[tuple[int, int], list[bool]] = {}

    watch_table = watchlist_model._meta.db_table
    try:
        with schema_editor.connection.cursor() as cursor:
            existing_tables = set(schema_editor.connection.introspection.table_names(cursor))
    except Exception:
        existing_tables = set()

    if watch_table in existing_tables:
        try:
            watch_rows = (
                watchlist_model.objects.using(db_alias)
                .values_list("user_id", "instrument_id")
                .distinct()
            )
            for user_id, instrument_id in watch_rows.iterator(chunk_size=1000):
                key = (user_id, instrument_id)
                value = states.setdefault(key, [False, False])
                value[1] = True
        except ProgrammingError:
            # 某些历史库可能已手动删除该表，跳过 watchlist 回填。
            pass

    position_rows = (
        position_model.objects.using(db_alias)
        .filter(quantity__gt=0)
        .values_list("user_id", "instrument_id")
        .distinct()
    )
    for user_id, instrument_id in position_rows.iterator(chunk_size=1000):
        key = (user_id, instrument_id)
        value = states.setdefault(key, [False, False])
        value[0] = True

    if not states:
        return

    batch = []
    for (user_id, instrument_id), (from_position, from_watchlist) in states.items():
        if not from_position and not from_watchlist:
            continue
        batch.append(
            subscription_model(
                user_id=user_id,
                instrument_id=instrument_id,
                from_position=from_position,
                from_watchlist=from_watchlist,
            )
        )

        if len(batch) >= 1000:
            subscription_model.objects.using(db_alias).bulk_create(batch, ignore_conflicts=True)
            batch.clear()

    if batch:
        subscription_model.objects.using(db_alias).bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_move_instrument_to_market_app"),
        ("investment", "0002_position_realized_pnl_total"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInstrumentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("from_position", models.BooleanField(default=False)),
                ("from_watchlist", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriptions",
                        to="market.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "market_user_instrument_subscription",
                "indexes": [
                    models.Index(fields=["instrument"], name="mkt_sub_instrument_idx"),
                    models.Index(fields=["user", "updated_at"], name="mkt_sub_user_updated_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userinstrumentsubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "instrument"),
                name="uniq_user_instrument_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinstrumentsubscription",
            constraint=models.CheckConstraint(
                **_check_kwargs(Q(("from_position", True)) | Q(("from_watchlist", True))),
                name="sub_at_least_one_source_true",
            ),
        ),
        migrations.RunPython(_backfill_subscriptions, reverse_code=migrations.RunPython.noop),
    ]
