# Generated by Django 5.0.14 on 2026-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_userinstrumentsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="logo_source",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Logo 来源"
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="logo_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Logo 更新时间"
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="logo_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Logo URL"
            ),
        ),
    ]
