# Generated by Django 6.0.1 on 2026-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_instrument_asset_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否可交易"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="symbol",
            field=models.CharField(max_length=50, unique=True, verbose_name="标准代码"),
        ),
    ]
