# Generated by Django 5.0.14 on 2026-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_instrument_logo_source_instrument_logo_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="logo_color",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Logo 主题色"
            ),
        ),
    ]
