# Generated by Django 6.0.1 on 2026-03-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_remove_instrument_market_inst_short_c_cb36ea_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinstrumentsubscription",
            options={"verbose_name": "标的订阅", "verbose_name_plural": "标的订阅"},
        ),
    ]
