# Generated by Django 5.0.14 on 2026-03-03 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24)),
                ("type", models.CharField(max_length=16)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="CNY",
                        max_length=3,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("archived", "归档"),
                            ("disabled", "禁用"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counterparty", models.CharField(max_length=32)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("category_name", models.CharField(max_length=24)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="CNY",
                        max_length=3,
                    ),
                ),
                ("add_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_tx",
                        to="accounts.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_transaction",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="accounts",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name", "投资账户"), ("type", "investment")),
                fields=("user",),
                name="uniq_user_investment_named_account",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accounts",
            unique_together={("user", "name", "currency")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "account", "-created_at", "-id"],
                name="accounts_tr_user_id_3b3054_idx",
            ),
        ),
    ]
