# Generated by Django 5.0 on 2026-01-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="name",
            field=models.CharField(max_length=24),
        ),
    ]
