# Generated by Django 5.0.14 on 2026-03-09 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transaction_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="remark",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "手工记账"),
                    ("investment", "投资交易"),
                    ("transfer", "账户转账"),
                    ("reversal", "冲正流水"),
                ],
                db_index=True,
                default="manual",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="CNY",
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("note", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("reversed", "已撤销")],
                        db_index=True,
                        default="success",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "in_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_inbound",
                        to="accounts.transaction",
                    ),
                ),
                (
                    "out_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_outbound",
                        to="accounts.transaction",
                    ),
                ),
                (
                    "reversed_in_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_reversed_inbound",
                        to="accounts.transaction",
                    ),
                ),
                (
                    "reversed_out_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_reversed_outbound",
                        to="accounts.transaction",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_transfer",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at", "-id"],
                        name="accounts_tr_user_id_f0558c_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_account", models.F("to_account")), _negated=True),
                name="transfer_from_to_account_not_equal",
            ),
        ),
    ]
