# Generated by Django 6.0.1 on 2026-03-12 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_transaction_remark_alter_transaction_source_transfer_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accounts",
            unique_together={("user", "name", "type", "currency")},
        ),
    ]
