# Generated by Django 6.0.1 on 2026-02-01 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_accounts_balance_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="add_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
