# Generated by Django 6.0.1 on 2026-02-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_transaction_add_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
