# Generated by Django 6.0.1 on 2026-03-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_transaction_transfer_account_remove_transfer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounts",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "账户",
                "verbose_name_plural": "账户",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "交易流水",
                "verbose_name_plural": "交易流水",
            },
        ),
    ]
