# Generated by Django 6.0.1 on 2026-02-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_transaction_balance_after"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_tx",
                to="accounts.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "account", "-created_at", "-id"],
                name="accounts_tr_user_id_3b3054_idx",
            ),
        ),
    ]
