# Generated by Django 6.0.1 on 2026-02-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_transaction_options_transaction_reversal_of_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_class", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=32)),
                ("symbol", models.CharField(max_length=64)),
                ("market", models.CharField(blank=True, max_length=16, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbols",
                        to="accounts.instrument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "market"],
                        name="accounts_in_vendor_4ddc31_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vendor", "symbol"), name="uniq_vendor_symbol"
                    )
                ],
            },
        ),
    ]
