# Generated by Django 6.0.1 on 2026-02-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_instrument_instrumentsymbol"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="instrumentsymbol",
            name="accounts_in_vendor_4ddc31_idx",
        ),
        migrations.RemoveConstraint(
            model_name="instrumentsymbol",
            name="uniq_vendor_symbol",
        ),
        migrations.RemoveField(
            model_name="instrumentsymbol",
            name="instrument",
        ),
        migrations.DeleteModel(
            name="Instrument",
        ),
        migrations.DeleteModel(
            name="InstrumentSymbol",
        ),
    ]
