# Generated by Django 6.0.1 on 2026-02-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_remove_instrumentsymbol_accounts_in_vendor_4ddc31_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="标准代码",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="原始代码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="品种名称"
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("STOCK", "股票 (Stock)"),
                            ("CRYPTO", "加密货币 (Crypto)"),
                            ("FOREX", "外汇 (Forex)"),
                        ],
                        default="STOCK",
                        max_length=20,
                        verbose_name="资产大类",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("US", "美股 (United States)"),
                            ("CN", "A股 (China)"),
                            ("HK", "港股 (Hong Kong)"),
                            ("CRYPTO", "加密货币市场 (Crypto)"),
                            ("FX", "外汇市场 (Forex)"),
                        ],
                        default="US",
                        max_length=20,
                        verbose_name="所属市场",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="交易所"
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="计价货币"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="用于标记退市股票或下架品种",
                        verbose_name="是否可交易",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "交易品种",
                "verbose_name_plural": "交易品种列表",
                "ordering": ["asset_class", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["short_code", "name"],
                        name="accounts_in_short_c_69a152_idx",
                    )
                ],
            },
        ),
    ]
