# Generated by Django 6.0.1 on 2026-02-27 00:10

import django.db.models.deletion
from django.core.management.color import no_style
from django.db import migrations, models


COPY_FIELDS = (
    "symbol",
    "short_code",
    "name",
    "asset_class",
    "market",
    "exchange",
    "base_currency",
    "is_active",
    "created_at",
    "updated_at",
)


def _reset_sequence(schema_editor, model):
    sequence_sql = schema_editor.connection.ops.sequence_reset_sql(no_style(), [model])
    if not sequence_sql:
        return

    with schema_editor.connection.cursor() as cursor:
        for sql in sequence_sql:
            cursor.execute(sql)


def copy_instruments_to_market(apps, schema_editor):
    source_model = apps.get_model("accounts", "Instrument")
    target_model = apps.get_model("market", "Instrument")
    db_alias = schema_editor.connection.alias

    batch = []
    for source in source_model.objects.using(db_alias).all().iterator(chunk_size=1000):
        payload = {field: getattr(source, field) for field in COPY_FIELDS}
        batch.append(target_model(id=source.id, **payload))

        if len(batch) >= 1000:
            target_model.objects.using(db_alias).bulk_create(batch, ignore_conflicts=True)
            batch.clear()

    if batch:
        target_model.objects.using(db_alias).bulk_create(batch, ignore_conflicts=True)

    _reset_sequence(schema_editor, target_model)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_watchlistitem"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_instruments_to_market, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="watchlistitem",
            name="instrument",
            field=models.ForeignKey(
                db_index=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.instrument",
            ),
        ),
        migrations.DeleteModel(
            name="Instrument",
        ),
    ]
