# Generated by Django 5.0.14 on 2026-03-01 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_move_instrument_to_market_app"),
        ("market", "0002_userinstrumentsubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WatchlistItem",
        ),
    ]
