# Generated by Django 5.0.14 on 2026-03-02 12:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_delete_watchlistitem"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accounts",
            constraint=models.UniqueConstraint(
                condition=Q(name="投资账户", type="investment"),
                fields=("user",),
                name="uniq_user_investment_named_account",
            ),
        ),
    ]
