# Generated by Django 6.0.1 on 2026-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_investment_account_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "人民币"),
                    ("USD", "美元"),
                    ("JPY", "日元"),
                    ("EUR", "欧元"),
                    ("HKD", "港币"),
                ],
                default="CNY",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "人民币"),
                    ("USD", "美元"),
                    ("JPY", "日元"),
                    ("EUR", "欧元"),
                    ("HKD", "港币"),
                ],
                default="CNY",
                max_length=3,
            ),
        ),
    ]
