"""
Django settings for mango_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
from kombu import Queue

try:
    import django_redis  # noqa: F401
except Exception:
    CACHE_BACKEND = "django.core.cache.backends.redis.RedisCache"
    CACHE_OPTIONS = {}
else:
    CACHE_BACKEND = "django_redis.cache.RedisCache"
    CACHE_OPTIONS = {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
    }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
RESOURCE_DIR = BASE_DIR / "resource"
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)


def _load_dotenv_file(path: Path) -> None:
    # Prefer python-dotenv if installed; fallback to a minimal parser.
    try:
        from dotenv import load_dotenv  # type: ignore
    except Exception:
        if not path.exists():
            return
        for line in path.read_text(encoding="utf-8").splitlines():
            raw = line.strip()
            if not raw or raw.startswith("#") or "=" not in raw:
                continue
            key, value = raw.split("=", 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue
            if value and len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
                value = value[1:-1]
            os.environ.setdefault(key, value)
        return
    load_dotenv(path)


_load_dotenv_file(BASE_DIR / ".env")


def _env_bool(name: str, default: str = "false") -> bool:
    return os.getenv(name, default).strip().lower() in {"1", "true", "yes", "on"}


def _env_csv(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default).replace("，", ",")
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", "true")

ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_filters',

    'corsheaders',

    'rest_framework',
    'rest_framework_simplejwt',
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    'login',
    'accounts',
    'market',
    'investment',
    'snapshot',
    'news',
    'ai',

]

# Django DRF配置
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "EXCEPTION_HANDLER": "common.exception.custom_exception_handler",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Mango Finance API",
    "DESCRIPTION": "API 文档",
    "VERSION": "1.0.0",
}


# JWT过期时间 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    "BLACKLIST_AFTER_ROTATION": False,
}

# 中间件链配置
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 允许跨域
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = _env_csv(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "https://mangofinance.cc,https://www.mangofinance.cc,https://api.mangofinance.cc",
)
CSRF_TRUSTED_ORIGINS = _env_csv(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    ",".join(CORS_ALLOWED_ORIGINS),
)

CORS_ALLOW_CREDENTIALS = True


# redis配置
CACHES = {
    "default": {
        "BACKEND": CACHE_BACKEND,
        "LOCATION": "redis://127.0.0.1:6379/1",  # 使用 Redis 1 号数据库
        "OPTIONS": CACHE_OPTIONS,
        "KEY_FUNCTION": "common.utils.redis_cache_key",
    }
}
REDIS_TIMEOUT=7*24*60*60
CUBES_REDIS_TIMEOUT=60*60
NEVER_REDIS_TIMEOUT=365*24*60*60
WATCHLIST_ORPHAN_QUOTE_TTL=30*60
INVESTMENT_QUOTE_WARMUP_ENABLED = True
LOGO_DEV_IMAGE_BASE_URL = os.getenv("LOGO_DEV_IMAGE_BASE_URL", "https://img.logo.dev").strip().rstrip("/")
LOGO_DEV_PUBLISHABLE_KEY = os.getenv(
    "LOGO_DEV_PUBLISHABLE_KEY",
    os.getenv("LOGO_DEV_API_KEY", ""),
).strip()
LOGO_DOWNLOAD_DIR = os.getenv("LOGO_DOWNLOAD_DIR", str((RESOURCE_DIR / "logo_downloads").resolve())).strip()
MARKET_PULL_TASK_INTERVAL_MINUTES = int(os.getenv("MARKET_PULL_TASK_INTERVAL_MINUTES", "5"))
MARKET_PULL_INTERVAL_MINUTES = int(os.getenv("MARKET_PULL_INTERVAL_MINUTES", "10"))
MARKET_FX_PULL_INTERVAL_MINUTES = int(os.getenv("MARKET_FX_PULL_INTERVAL_MINUTES", "240"))
MARKET_CRYPTO_PULL_INTERVAL_MINUTES = int(os.getenv("MARKET_CRYPTO_PULL_INTERVAL_MINUTES", "10"))

SNAPSHOT_AGG_H4_CRON_MINUTE = int(os.getenv("SNAPSHOT_AGG_H4_CRON_MINUTE", "0"))
SNAPSHOT_AGG_D1_CRON_HOUR = int(os.getenv("SNAPSHOT_AGG_D1_CRON_HOUR", "0"))
SNAPSHOT_AGG_D1_CRON_MINUTE = int(os.getenv("SNAPSHOT_AGG_D1_CRON_MINUTE", "0"))

SNAPSHOT_AGG_MON1_CRON_DAY = int(os.getenv("SNAPSHOT_AGG_MON1_CRON_DAY", "1"))
SNAPSHOT_AGG_MON1_CRON_HOUR = int(os.getenv("SNAPSHOT_AGG_MON1_CRON_HOUR", "0"))
SNAPSHOT_AGG_MON1_CRON_MINUTE = int(os.getenv("SNAPSHOT_AGG_MON1_CRON_MINUTE", "0"))

SNAPSHOT_CLEANUP_CRON_HOUR = int(os.getenv("SNAPSHOT_CLEANUP_CRON_HOUR", "1"))
SNAPSHOT_CLEANUP_CRON_MINUTE = int(os.getenv("SNAPSHOT_CLEANUP_CRON_MINUTE", "45"))
AI_NEWS_ANALYSIS_INTERVAL_MINUTES = int(os.getenv("AI_NEWS_ANALYSIS_INTERVAL_MINUTES", "15"))
AI_NEWS_EMBEDDING_INTERVAL_MINUTES = int(os.getenv("AI_NEWS_EMBEDDING_INTERVAL_MINUTES", "15"))

CELERY_BEAT_MAX_LOOP_INTERVAL = int(os.getenv("CELERY_BEAT_MAX_LOOP_INTERVAL", "5"))


# Celery 配置

# Broker配置，使用RabbitMQ作为消息中间件
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "pyamqp://guest:guest@127.0.0.1:5672//")
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_CREATE_MISSING_QUEUES = True
CELERY_TASK_QUEUES = (
    Queue("market_sync", queue_arguments={"x-message-ttl": 2400}),
    Queue("snapshot_capture", queue_arguments={"x-message-ttl": 7200}),
    Queue("snapshot_aggregate"),
    Queue("snapshot_cleanup"),
    Queue("news_ingest"),
    Queue("news_embedding"),
    Queue("ai_analysis"),
)

CELERY_BEAT_SCHEDULE = {
    "pull-watchlist-quotes-every-5-minutes": {
        "task": "market.tasks.task_refresh_all",
        "schedule": crontab(minute="*/10"),
        "options": {"expires": 240},
    },
    "capture-snapshot-m15": {
        "task": "snapshot.tasks.task_capture_m15_snapshots",
        "schedule": crontab(minute="*/15"),
        "options": {"expires": 12 * 60},
    },
    "aggregate-snapshot-h4": {
        "task": "snapshot.tasks.task_aggregate_h4_snapshots",
        "schedule": crontab(minute=SNAPSHOT_AGG_H4_CRON_MINUTE, hour="*/4"),
        "options": {"expires": 90 * 60},
    },
    "aggregate-snapshot-d1": {
        "task": "snapshot.tasks.task_aggregate_d1_snapshots",
        "schedule": crontab(minute=SNAPSHOT_AGG_D1_CRON_MINUTE, hour=SNAPSHOT_AGG_D1_CRON_HOUR),
        "options": {"expires": 6 * 60 * 60},
    },
    "aggregate-snapshot-mon1": {
        "task": "snapshot.tasks.task_aggregate_mon1_snapshots",
        "schedule": crontab(
            minute=SNAPSHOT_AGG_MON1_CRON_MINUTE,
            hour=SNAPSHOT_AGG_MON1_CRON_HOUR,
            day_of_month=SNAPSHOT_AGG_MON1_CRON_DAY,
        ),
        "options": {"expires": 2 * 24 * 60 * 60},
    },
    "cleanup-snapshot-history-daily": {
        "task": "snapshot.tasks.task_cleanup_snapshot_history",
        "schedule": crontab(hour=SNAPSHOT_CLEANUP_CRON_HOUR, minute=SNAPSHOT_CLEANUP_CRON_MINUTE),
        "options": {"expires": 24 * 60 * 60},
    },
    "analyze-pending-news-every-n-minutes": {
        "task": "ai.tasks.task_analyze_pending_news_articles",
        "schedule": crontab(minute=f"*/{AI_NEWS_ANALYSIS_INTERVAL_MINUTES}"),
        "options": {"expires": max(AI_NEWS_ANALYSIS_INTERVAL_MINUTES * 60 - 5, 30)},
    },
    "embed-missing-news-every-n-minutes": {
        "task": "news.tasks.task_embed_missing_news_articles",
        "schedule": crontab(minute=f"*/{AI_NEWS_EMBEDDING_INTERVAL_MINUTES}"),
        "options": {"expires": max(AI_NEWS_EMBEDDING_INTERVAL_MINUTES * 60 - 5, 30)},
    },
    "analyze-missing-news-every-n-minutes": {
        "task": "ai.tasks.task_analyze_missing_news_articles",
        "schedule": crontab(minute=f"*/{AI_NEWS_ANALYSIS_INTERVAL_MINUTES}"),
        "options": {"expires": max(AI_NEWS_ANALYSIS_INTERVAL_MINUTES * 60 - 5, 30)},
    },
}

CELERY_TASK_ROUTES = {
    "market.tasks.task_refresh_all": {"queue": "market_sync"},
    "snapshot.tasks.task_capture_m15_snapshots": {"queue": "snapshot_capture"},
    "snapshot.tasks.task_aggregate_h4_snapshots": {"queue": "snapshot_aggregate"},
    "snapshot.tasks.task_aggregate_d1_snapshots": {"queue": "snapshot_aggregate"},
    "snapshot.tasks.task_aggregate_mon1_snapshots": {"queue": "snapshot_aggregate"},
    "snapshot.tasks.task_cleanup_snapshot_history": {"queue": "snapshot_cleanup"},
    "news.tasks.task_ingest_yahoo_news": {"queue": "news_ingest"},
    "news.tasks.task_embed_news_article": {"queue": "news_embedding"},
    "news.tasks.task_embed_missing_news_articles": {"queue": "news_embedding"},
    "ai.tasks.task_analyze_news_article": {"queue": "ai_analysis"},
    "ai.tasks.task_analyze_missing_news_articles": {"queue": "ai_analysis"},
    "ai.tasks.task_analyze_pending_news_articles": {"queue": "ai_analysis"},
}



ROOT_URLCONF = "mango_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mango_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库
DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.sqlite3",
        # "NAME": BASE_DIR / "db.sqlite3",
        'ENGINE': os.getenv("DB_ENGINE", 'django.db.backends.postgresql'),
        'NAME': os.getenv("DB_NAME", 'mango_project_db'),
        'USER': os.getenv("DB_USER", 'postgres'),
        'PASSWORD': os.getenv("DB_PASSWORD", ''),
        'HOST': os.getenv("DB_HOST", '127.0.0.1'),
        'PORT': os.getenv("DB_PORT", '5432'),

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 邮箱配置
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.163.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", "true")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", "false")

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", f"Mango_Finance <{EMAIL_HOST_USER or 'no-reply@example.com'}>")


# 日志配置
default_handlers = ["console"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "ai_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "standard",
            "filename": str(LOG_DIR / "ai.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "market": {
            "handlers": default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "accounts": {
            "handlers": default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "celery.app.trace": {
            "handlers": default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "ai_log": {
            "handlers": ["ai_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
