"""
Django settings for mango_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab

try:
    import django_redis  # noqa: F401
except Exception:
    CACHE_BACKEND = "django.core.cache.backends.redis.RedisCache"
    CACHE_OPTIONS = {}
else:
    CACHE_BACKEND = "django_redis.cache.RedisCache"
    CACHE_OPTIONS = {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
    }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*p_=+200g*)n4a*f2f0=ri#v0z+0c-yi)ktvv#l5u7l9kzqt$u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_filters',

    'corsheaders',

    'rest_framework',
    'rest_framework_simplejwt',


    'login',
    'accounts',
    'market',
    'investment',

]

# Django DRF配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}
# JWT过期时间 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

# 中间件链配置
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
     # 找到当前用户id
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 允许跨域
CORS_ALLOW_ALL_ORIGINS = True



# redis配置
CACHES = {
    "default": {
        "BACKEND": CACHE_BACKEND,
        "LOCATION": "redis://127.0.0.1:6379/1",  # 这里�?1 代表使用 Redis �?1 号数据库
        "OPTIONS": CACHE_OPTIONS
    }
}
REDIS_TIMEOUT=7*24*60*60
CUBES_REDIS_TIMEOUT=60*60
NEVER_REDIS_TIMEOUT=365*24*60*60
WATCHLIST_ORPHAN_QUOTE_TTL=30*60
INVESTMENT_QUOTE_WARMUP_ENABLED = True
LOGO_DEV_IMAGE_BASE_URL = os.getenv("LOGO_DEV_IMAGE_BASE_URL", "https://img.logo.dev").strip().rstrip("/")
LOGO_DEV_PUBLISHABLE_KEY = os.getenv(
    "LOGO_DEV_PUBLISHABLE_KEY",
    os.getenv("LOGO_DEV_API_KEY", "pk_LgAIO0lqStWd7Xgj7Tx0Og"),
).strip()
LOGO_DOWNLOAD_DIR = os.getenv("LOGO_DOWNLOAD_DIR", str((BASE_DIR.parent / "logo_downloads").resolve())).strip()


# Celery 配置

# Broker配置，使用Redis作为消息中间件
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = True

CELERY_BEAT_SCHEDULE = {
    "pull-watchlist-quotes-every-10-minutes": {
        "task": "accounts.tasks.task_pull_watchlist_quotes",
        "schedule": crontab(minute="*/10"),
    },
}



ROOT_URLCONF = "mango_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mango_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库配�?
DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.sqlite3",
        # "NAME": BASE_DIR / "db.sqlite3",
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mango_project_db',
        'USER': 'postgres',
        'PASSWORD': '113150',
        'HOST': '127.0.0.1',
        'PORT': '5432',

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 邮箱配置
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 465
EMAIL_USE_SSL = True          # 465 用 SSL
EMAIL_USE_TLS = False         # SSL 与 TLS 二选一，别同时开

EMAIL_HOST_USER = "wryto_11@163.com"
EMAIL_HOST_PASSWORD = "SNdJu35w6fdCNYkG"

DEFAULT_FROM_EMAIL = "Mango_Finance <wryto_11@163.com>"


# 日志配置
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "market": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "accounts": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}




