# Generated by Django 5.0.14 on 2026-03-03 17:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django import VERSION as DJANGO_VERSION
from django.conf import settings
from django.db import migrations, models


def _check_kwargs(expr):
    if DJANGO_VERSION >= (5, 1):
        return {"condition": expr}
    return {"check": expr}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentPositionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_time", models.DateTimeField(db_index=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("price_time", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[("ok", "正常"), ("quote_missing", "缺少行情")],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_position_snapshots",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_position_snapshots",
                        to="market.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "investment_position_snapshot",
            },
        ),
        migrations.CreateModel(
            name="InvestmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("SELL", "SELL")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "trade_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_records",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_records",
                        to="market.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investment_record",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "cost_total",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "realized_pnl_total",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="market.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investment_position",
            },
        ),
        migrations.CreateModel(
            name="InvestmentAccountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_time", models.DateTimeField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "人民币"),
                            ("USD", "美元"),
                            ("JPY", "日元"),
                            ("EUR", "欧元"),
                            ("HKD", "港币"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("total_asset", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "data_status",
                    models.CharField(
                        choices=[("ok", "正常"), ("quote_missing", "缺少行情")],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_account_snapshots",
                        to="accounts.accounts",
                    ),
                ),
            ],
            options={
                "db_table": "investment_account_snapshot",
                "indexes": [
                    models.Index(
                        fields=["account", "snapshot_time"],
                        name="inv_acc_snap_acc_time_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="investmentaccountsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "snapshot_time"), name="uniq_inv_acc_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentaccountsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("total_asset__gte", 0))),
                name="inv_acc_snapshot_total_asset_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentpositionsnapshot",
            index=models.Index(
                fields=["account", "snapshot_time"], name="inv_pos_snap_acc_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "instrument", "snapshot_time"),
                name="uniq_inv_pos_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("quantity__gte", 0))),
                name="inv_pos_snapshot_quantity_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("avg_cost__gte", 0))),
                name="inv_pos_snapshot_avg_cost_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("market_price__isnull", True),
                    ("market_price__gt", 0),
                    _connector="OR",
                )),
                name="inv_pos_snapshot_market_price_null_or_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    ("market_value__isnull", True),
                    ("market_value__gte", 0),
                    _connector="OR",
                )),
                name="inv_pos_snapshot_market_value_null_or_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    models.Q(
                        ("data_status", "ok"),
                        ("market_price__isnull", False),
                        ("market_value__isnull", False),
                    ),
                    ("data_status", "quote_missing"),
                    _connector="OR",
                )),
                name="inv_pos_snapshot_status_price_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentrecord",
            index=models.Index(
                fields=["user", "trade_at"], name="investment__user_id_5c19c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentrecord",
            index=models.Index(
                fields=["user", "instrument", "trade_at"],
                name="investment__user_id_f54229_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentrecord",
            index=models.Index(
                fields=["cash_account", "trade_at"],
                name="investment__cash_ac_1fa41f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentrecord",
            index=models.Index(
                fields=["user", "side", "trade_at"],
                name="investment__user_id_b9f1d6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentrecord",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("quantity__gt", 0))), name="invrec_quantity_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentrecord",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("price__gt", 0))), name="invrec_price_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentrecord",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    models.Q(("realized_pnl__isnull", True), ("side", "BUY")),
                    ("side", "SELL"),
                    _connector="OR",
                )),
                name="invrec_buy_realized_pnl_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentrecord",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    models.Q(("realized_pnl__isnull", False), ("side", "SELL")),
                    ("side", "BUY"),
                    _connector="OR",
                )),
                name="invrec_sell_realized_pnl_not_null",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["user", "updated_at"], name="investment__user_id_26ec0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("user", "instrument"), name="uniq_user_instrument_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("quantity__gte", 0))), name="pos_quantity_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("avg_cost__gte", 0))), name="pos_avg_cost_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(("cost_total__gte", 0))), name="pos_cost_total_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                **_check_kwargs(models.Q(
                    models.Q(("avg_cost", 0), ("cost_total", 0), ("quantity", 0)),
                    ("quantity__gt", 0),
                    _connector="OR",
                )),
                name="pos_zero_qty_means_zero_cost",
            ),
        ),
    ]
