# Generated by Django 6.0.1 on 2026-02-28 08:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django import VERSION as DJANGO_VERSION
from django.conf import settings
from django.db import migrations, models


def _check_kwargs(expr):
    if DJANGO_VERSION >= (5, 1):
        return {"condition": expr}
    return {"check": expr}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0011_move_instrument_to_market_app"),
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("SELL", "SELL")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "trade_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_records",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_records",
                        to="market.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investment_record",
                "indexes": [
                    models.Index(
                        fields=["user", "trade_at"],
                        name="investment__user_id_5c19c1_idx",
                    ),
                    models.Index(
                        fields=["user", "instrument", "trade_at"],
                        name="investment__user_id_f54229_idx",
                    ),
                    models.Index(
                        fields=["cash_account", "trade_at"],
                        name="investment__cash_ac_1fa41f_idx",
                    ),
                    models.Index(
                        fields=["user", "side", "trade_at"],
                        name="investment__user_id_b9f1d6_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(("quantity__gt", 0))),
                        name="invrec_quantity_gt_0",
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(("price__gt", 0))), name="invrec_price_gt_0"
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(
                            models.Q(("realized_pnl__isnull", True), ("side", "BUY")),
                            ("side", "SELL"),
                            _connector="OR",
                        )),
                        name="invrec_buy_realized_pnl_null",
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(
                            models.Q(("realized_pnl__isnull", False), ("side", "SELL")),
                            ("side", "BUY"),
                            _connector="OR",
                        )),
                        name="invrec_sell_realized_pnl_not_null",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "cost_total",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="market.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investment_position",
                "indexes": [
                    models.Index(
                        fields=["user", "updated_at"],
                        name="investment__user_id_26ec0b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "instrument"),
                        name="uniq_user_instrument_position",
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(("quantity__gte", 0))),
                        name="pos_quantity_gte_0",
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(("avg_cost__gte", 0))),
                        name="pos_avg_cost_gte_0",
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(("cost_total__gte", 0))),
                        name="pos_cost_total_gte_0",
                    ),
                    models.CheckConstraint(
                        **_check_kwargs(models.Q(
                            models.Q(
                                ("avg_cost", 0), ("cost_total", 0), ("quantity", 0)
                            ),
                            ("quantity__gt", 0),
                            _connector="OR",
                        )),
                        name="pos_zero_qty_means_zero_cost",
                    ),
                ],
            },
        ),
    ]
