# Generated by Django 5.0.14 on 2026-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("investment", "0001_initial"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="investmentaccountsnapshot",
            name="uniq_inv_acc_snapshot",
        ),
        migrations.RemoveConstraint(
            model_name="investmentpositionsnapshot",
            name="uniq_inv_pos_snapshot",
        ),
        migrations.RemoveIndex(
            model_name="investmentaccountsnapshot",
            name="inv_acc_snap_acc_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="investmentpositionsnapshot",
            name="inv_pos_snap_acc_time_idx",
        ),
        migrations.AddField(
            model_name="investmentaccountsnapshot",
            name="snapshot_level",
            field=models.CharField(
                choices=[
                    ("M15", "15分钟"),
                    ("H4", "4小时"),
                    ("D1", "1天"),
                    ("MON1", "1月"),
                ],
                default="M15",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="investmentpositionsnapshot",
            name="snapshot_level",
            field=models.CharField(
                choices=[
                    ("M15", "15分钟"),
                    ("H4", "4小时"),
                    ("D1", "1天"),
                    ("MON1", "1月"),
                ],
                default="M15",
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="investmentaccountsnapshot",
            index=models.Index(
                fields=["account", "snapshot_level", "snapshot_time"],
                name="inv_acc_snap_acc_lvl_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentaccountsnapshot",
            index=models.Index(
                fields=["snapshot_level", "snapshot_time"],
                name="inv_acc_snap_lvl_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentpositionsnapshot",
            index=models.Index(
                fields=["account", "instrument", "snapshot_level", "snapshot_time"],
                name="inv_pos_acc_inst_lvl_t_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentpositionsnapshot",
            index=models.Index(
                fields=["snapshot_level", "snapshot_time"],
                name="inv_pos_snap_lvl_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentaccountsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "snapshot_level", "snapshot_time"),
                name="uniq_inv_acc_snapshot_lvl",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentpositionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "instrument", "snapshot_level", "snapshot_time"),
                name="uniq_inv_pos_snapshot_lvl",
            ),
        ),
    ]
