# Generated by Django 5.0.14 on 2026-03-01 08:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="realized_pnl_total",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=20
            ),
        ),
    ]
