# Generated by Django 5.0.14 on 2026-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "investment",
            "0002_remove_investmentaccountsnapshot_uniq_inv_acc_snapshot_and_more",
        ),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="investmentaccountsnapshot",
            name="inv_acc_snap_acc_lvl_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="investmentpositionsnapshot",
            name="inv_pos_acc_inst_lvl_t_idx",
        ),
        migrations.AddIndex(
            model_name="investmentpositionsnapshot",
            index=models.Index(
                fields=["account", "snapshot_level", "snapshot_time"],
                name="inv_pos_acc_lvl_time_idx",
            ),
        ),
    ]
