# Generated by Django 5.0.14 on 2026-03-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0003_remove_investmentaccountsnapshot_inv_acc_snap_acc_lvl_time_idx_and_more"),
        ("snapshot", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="InvestmentAccountSnapshot"),
                migrations.DeleteModel(name="InvestmentPositionSnapshot"),
            ],
        ),
    ]
