# Generated by Django 6.0.1 on 2026-03-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0005_investmentrecord_cash_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentrecord",
            options={"verbose_name": "投资记录", "verbose_name_plural": "投资记录"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "持仓", "verbose_name_plural": "持仓"},
        ),
    ]
