# Generated by Django 6.0.1 on 2026-03-21 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_accounts_options_alter_transaction_options"),
        ("investment", "0007_update_investmentrecord_indexes"),
        ("market", "0006_alter_userinstrumentsubscription_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="investmentrecord",
            name="invrec_buy_realized_pnl_null",
        ),
        migrations.RemoveConstraint(
            model_name="investmentrecord",
            name="invrec_sell_realized_pnl_not_null",
        ),
        migrations.AddConstraint(
            model_name="investmentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("realized_pnl__isnull", True), ("side", "BUY")),
                    models.Q(("realized_pnl__isnull", False), ("side", "SELL")),
                    _connector="OR",
                ),
                name="invrec_side_realized_pnl_consistent",
            ),
        ),
    ]
