# Generated by Django 6.0.1 on 2026-03-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0006_alter_userinstrumentsubscription_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("news_article", "News Article")],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("source_id", models.BigIntegerField(db_index=True)),
                ("topic", models.CharField(db_index=True, max_length=100)),
                ("summary_short", models.TextField()),
                ("summary_long", models.TextField()),
                ("sentiment", models.CharField(db_index=True, max_length=20)),
                ("impact_level", models.CharField(db_index=True, max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_name", models.CharField(max_length=100)),
                ("analyzed_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-analyzed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="ai_aianalys_source__1f6a80_idx",
                    ),
                    models.Index(
                        fields=["topic", "analyzed_at"],
                        name="ai_aianalys_topic_261fb4_idx",
                    ),
                    models.Index(
                        fields=["sentiment", "impact_level"],
                        name="ai_aianalys_sentime_567b8d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(db_index=True, max_length=100)),
                (
                    "ai_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_links",
                        to="ai.aianalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["country_name"],
                        name="ai_aianaly_country_57a754_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ai_analysis", "country_name"),
                        name="uniq_ai_analysis_country",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(db_index=True, max_length=100)),
                (
                    "ai_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="ai.aianalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["tag_name"],
                        name="ai_aianaly_tag_nam_70f7fe_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ai_analysis", "tag_name"),
                        name="uniq_ai_analysis_tag",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_links",
                        to="ai.aianalysis",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis_links",
                        to="market.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["instrument"],
                        name="ai_aianaly_instrum_c9438f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ai_analysis", "instrument"),
                        name="uniq_ai_analysis_instrument",
                    ),
                ],
            },
        ),
    ]
