# Generated by Django 6.0.1 on 2026-03-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aianalysis",
            new_name="ai_aianalys_source__676100_idx",
            old_name="ai_aianalys_source__1f6a80_idx",
        ),
        migrations.RenameIndex(
            model_name="aianalysis",
            new_name="ai_aianalys_topic_a27d2a_idx",
            old_name="ai_aianalys_topic_261fb4_idx",
        ),
        migrations.RenameIndex(
            model_name="aianalysis",
            new_name="ai_aianalys_sentime_b063e9_idx",
            old_name="ai_aianalys_sentime_567b8d_idx",
        ),
        migrations.RenameIndex(
            model_name="aianalysiscountry",
            new_name="ai_aianalys_country_6f784e_idx",
            old_name="ai_aianaly_country_57a754_idx",
        ),
        migrations.RenameIndex(
            model_name="aianalysisinstrument",
            new_name="ai_aianalys_instrum_e20438_idx",
            old_name="ai_aianaly_instrum_c9438f_idx",
        ),
        migrations.RenameIndex(
            model_name="aianalysistag",
            new_name="ai_aianalys_tag_nam_e8377f_idx",
            old_name="ai_aianaly_tag_nam_70f7fe_idx",
        ),
    ]
